In [1]:
x=5
x

5

In [3]:
# Write code here
import numpy as np


In [5]:
# Write code here
m=np.zeros((5,5))
m[0,:]=1
m[4,:]=1
m[:,0]=1
m[:,4]=1
print(m)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
# Write code here
a=np.full((5,5),3)
np.fill_diagonal(a,1)
n = a.shape[0] 
a[np.arange(n), np.arange(n-1, -1, -1)] = 2
print(a)
print(n)

[[1 3 3 3 2]
 [3 1 3 2 3]
 [3 3 2 3 3]
 [3 2 3 1 3]
 [2 3 3 3 1]]
5


In [7]:
v1=np.array([5,3])
v2=np.array([3,-6])
b=np.array([-20,-10])
mat1=np.array([v1,v2])
b = b.reshape(2, 1)
matrix=np.hstack([mat1,b])
print(matrix)


[[  5   3 -20]
 [  3  -6 -10]]


In [8]:
# write the code here
amtrix1=np.random.randint(1,10,(5,5))
matrix2=np.random.randint(11,20,(5,5))
print(amtrix1)
print(matrix2)
print('total matrix')  
tolal=np.vstack([amtrix1,matrix2])    
print(tolal)    

[[7 6 8 6 6]
 [3 7 2 8 4]
 [4 1 6 2 6]
 [5 9 7 2 6]
 [9 8 6 9 3]]
[[17 13 16 13 14]
 [17 19 13 11 12]
 [19 17 18 15 19]
 [14 16 11 17 19]
 [14 16 13 14 13]]
total matrix
[[ 7  6  8  6  6]
 [ 3  7  2  8  4]
 [ 4  1  6  2  6]
 [ 5  9  7  2  6]
 [ 9  8  6  9  3]
 [17 13 16 13 14]
 [17 19 13 11 12]
 [19 17 18 15 19]
 [14 16 11 17 19]
 [14 16 13 14 13]]


In [11]:
x=3
x



3